=== StackStorm/st2/st2common/st2common/util/schema/custom.json
{
    "id": "http://json-schema.org/draft-04/schema#",
    "$schema": "http://json-schema.org/draft-04/schema#",
    "description": "Core schema meta-schema",
    "definitions": {
        "schemaArray": {
            "type": "array",
            "minItems": 1,
            "items": { "$ref": "#" }
        },
        "positiveInteger": {
            "type": "integer",
            "minimum": 0
        },
        "positiveIntegerDefault0": {
            "allOf": [ { "$ref": "#/definitions/positiveInteger" }, { "default": 0 } ]
        },
        "simpleTypes": {
            "enum": [ "array", "boolean", "integer", "null", "number", "object", "string", "raw_string" ]
        },
        "stringArray": {
            "type": "array",
            "items": { "type": "string" },
            "minItems": 1,
            "uniqueItems": true
        }
    },
    "type": "object",
    "properties": {
        "id": {
            "type": "string",
            "format": "uri"
        },
        "$schema": {
            "type": "string",
            "format": "uri"
        },
        "title": {
            "type": "string"
        },
        "description": {
            "type": "string"
        },
        "default": {},
        "multipleOf": {
            "type": "number",
            "minimum": 0,
            "exclusiveMinimum": true
        },
        "maximum": {
            "type": "number"
        },
        "exclusiveMaximum": {
            "type": "boolean",
            "default": false
        },
        "minimum": {
            "type": "number"
        },
        "exclusiveMinimum": {
            "type": "boolean",
            "default": false
        },
        "maxLength": { "$ref": "#/definitions/positiveInteger" },
        "minLength": { "$ref": "#/definitions/positiveIntegerDefault0" },
        "pattern": {
            "type": "string",
            "format": "regex"
        },
        "additionalItems": {
            "anyOf": [
                { "type": "boolean" },
                { "$ref": "#" }
            ],
            "default": {}
        },
        "items": {
            "anyOf": [
                { "$ref": "#" },
                { "$ref": "#/definitions/schemaArray" }
            ],
            "default": {}
        },
        "maxItems": { "$ref": "#/definitions/positiveInteger" },
        "minItems": { "$ref": "#/definitions/positiveIntegerDefault0" },
        "uniqueItems": {
            "type": "boolean",
            "default": false
        },
        "maxProperties": { "$ref": "#/definitions/positiveInteger" },
        "minProperties": { "$ref": "#/definitions/positiveIntegerDefault0" },
        "required": {
            "type": "boolean",
            "default": false
        },
        "secret": {
            "type": "boolean",
            "default": false
        },
        "additionalProperties": {
            "anyOf": [
                { "type": "boolean" },
                { "$ref": "#" }
            ],
            "default": {}
        },
        "definitions": {
            "type": "object",
            "additionalProperties": { "$ref": "#" },
            "default": {}
        },
        "properties": {
            "type": "object",
            "additionalProperties": { "$ref": "#" },
            "default": {}
        },
        "patternProperties": {
            "type": "object",
            "additionalProperties": { "$ref": "#" },
            "default": {}
        },
        "dependencies": {
            "type": "object",
            "additionalProperties": {
                "anyOf": [
                    { "$ref": "#" },
                    { "$ref": "#/definitions/stringArray" }
                ]
            }
        },
        "enum": {
            "type": "array",
            "minItems": 1,
            "uniqueItems": true
        },
        "type": {
            "anyOf": [
                { "$ref": "#/definitions/simpleTypes" },
                {
                    "type": "array",
                    "items": { "$ref": "#/definitions/simpleTypes" },
                    "minItems": 1,
                    "uniqueItems": true
                }
            ]
        },
        "position": {
            "type": "number",
            "minimum": 0
        },
        "immutable": {
            "type": "boolean",
            "default": false
        },
        "format": { "type": "string" },
        "allOf": { "$ref": "#/definitions/schemaArray" },
        "anyOf": { "$ref": "#/definitions/schemaArray" },
        "oneOf": { "$ref": "#/definitions/schemaArray" },
        "not": { "$ref": "#" }
    },
    "dependencies": {
        "exclusiveMaximum": [ "maximum" ],
        "exclusiveMinimum": [ "minimum" ]
    },
    "default": {},
    "additionalProperties": false
}

=== StackStorm/st2/contrib/schemas/pack.json
{
    "additionalProperties": true, 
    "type": "object", 
    "description": "Content pack schema.", 
    "properties": {
        "files": {
            "default": [], 
            "items": {
                "type": "string"
            }, 
            "type": "array", 
            "description": "A list of files inside the pack."
        }, 
        "name": {
            "required": true, 
            "type": "string", 
            "description": "Display name of the pack. If the name only contains lowercaseletters, digits and underscores, the \"ref\" field is not required."
        }, 
        "contributors": {
            "items": {
                "type": "string", 
                "maxLength": 100
            }, 
            "type": "array", 
            "description": "A list of people who have contributed to the pack. Format is: Name <email address> e.g. Tomaz Muraus <tomaz@stackstorm.com>."
        }, 
        "author": {
            "required": true, 
            "type": "string", 
            "description": "Pack author or authors."
        }, 
        "description": {
            "required": true, 
            "type": "string", 
            "description": "Brief description of the pack and the service it integrates with."
        }, 
        "system": {
            "default": {}, 
            "type": "object", 
            "description": "Specification for the system components and packages required for the pack."
        }, 
        "python_versions": {
            "additionalItems": true, 
            "description": "Major Python versions supported by this pack. E.g. \"2\" for Python 2.7.x and \"3\" for Python 3.6.x", 
            "minItems": 1, 
            "items": {
                "enum": [
                    "2", 
                    "3"
                ], 
                "type": "string"
            }, 
            "maxItems": 2, 
            "uniqueItems": true, 
            "type": "array"
        }, 
        "stackstorm_version": {
            "pattern": "^((>?>|>=|=|<=|<?<)\\s*[0-9]+\\.[0-9]+\\.[0-9]+?(\\s*,)?\\s*)+$", 
            "type": "string", 
            "description": "Required StackStorm version. Examples: \">1.6.0\", \">=1.8.0, <2.2.0\""
        }, 
        "email": {
            "type": "string", 
            "description": "E-mail of the pack author.", 
            "format": "email"
        }, 
        "version": {
            "pattern": "^(?:0|[1-9]\\d*)\\.(?:0|[1-9]\\d*)\\.(?:0|[1-9]\\d*)(?:-[\\da-z\\-]+(?:\\.[\\da-z\\-]+)*)?(?:\\+[\\da-z\\-]+(?:\\.[\\da-z\\-]+)*)?$", 
            "required": true, 
            "type": "string", 
            "description": "Pack version. Must follow the semver format (for instance, \"0.1.0\")."
        }, 
        "dependencies": {
            "default": [], 
            "items": {
                "type": "string"
            }, 
            "type": "array", 
            "description": "A list of other StackStorm packs this pack depends upon. The same format as in \"st2 pack install\" is used: \"<name or full URL>[=<version or git ref>]\"."
        }, 
        "keywords": {
            "default": [], 
            "items": {
                "type": "string"
            }, 
            "type": "array", 
            "description": "Keywords describing the pack."
        }, 
        "path": {
            "required": false, 
            "type": "string", 
            "description": "Location of the pack on disk in st2 system."
        }, 
        "ref": {
            "default": null, 
            "pattern": "^[a-z0-9_]+$", 
            "type": "string", 
            "description": "Reference for the pack, used as an internal id."
        }, 
        "id": {
            "default": null, 
            "type": "string", 
            "description": "Unique identifier for the pack."
        }, 
        "uid": {
            "type": "string"
        }
    }
}

=== StackStorm/st2/contrib/schemas/policy.json
{
    "additionalProperties": false, 
    "type": "object", 
    "properties": {
        "uid": {
            "type": "string"
        }, 
        "resource_ref": {
            "required": true, 
            "type": "string"
        }, 
        "metadata_file": {
            "default": "", 
            "type": "string", 
            "description": "Path to the metadata file relative to the pack directory."
        }, 
        "id": {
            "default": null, 
            "type": "string"
        }, 
        "description": {
            "type": "string"
        }, 
        "name": {
            "required": true, 
            "type": "string"
        }, 
        "parameters": {
            "additionalProperties": false, 
            "patternProperties": {
                "^\\w+$": {
                    "anyOf": [
                        {
                            "type": "array"
                        }, 
                        {
                            "type": "boolean"
                        }, 
                        {
                            "type": "integer"
                        }, 
                        {
                            "type": "number"
                        }, 
                        {
                            "type": "object"
                        }, 
                        {
                            "type": "string"
                        }
                    ]
                }
            }, 
            "type": "object"
        }, 
        "enabled": {
            "default": true, 
            "type": "boolean"
        }, 
        "policy_type": {
            "required": true, 
            "type": "string"
        }, 
        "ref": {
            "type": "string"
        }, 
        "pack": {
            "type": "string"
        }
    }, 
    "title": "Policy"
}

=== StackStorm/st2/contrib/schemas/alias.json
{
    "additionalProperties": false, 
    "properties": {
        "uid": {
            "type": "string"
        }, 
        "extra": {
            "type": "object", 
            "description": "Extra parameters, usually adapter-specific."
        }, 
        "immutable_parameters": {
            "type": "object", 
            "description": "Parameters to be passed to the action on every execution."
        }, 
        "result": {
            "type": "object", 
            "properties": {
                "extra": {
                    "type": "object"
                }, 
                "enabled": {
                    "type": "boolean"
                }, 
                "format": {
                    "type": "string"
                }
            }, 
            "description": "Execution message format."
        }, 
        "id": {
            "type": "string", 
            "description": "The unique identifier for the action alias."
        }, 
        "description": {
            "default": null, 
            "type": "string", 
            "description": "Description of the action alias."
        }, 
        "name": {
            "required": true, 
            "type": "string", 
            "description": "Name of the action alias."
        }, 
        "ack": {
            "type": "object", 
            "properties": {
                "append_url": {
                    "type": "boolean"
                }, 
                "extra": {
                    "type": "object"
                }, 
                "enabled": {
                    "type": "boolean"
                }, 
                "format": {
                    "type": "string"
                }
            }, 
            "description": "Acknowledgement message format."
        }, 
        "enabled": {
            "default": true, 
            "type": "boolean", 
            "description": "Flag indicating of action alias is enabled."
        }, 
        "metadata_file": {
            "default": "", 
            "type": "string", 
            "description": "Path to the metadata file relative to the pack directory."
        }, 
        "formats": {
            "items": {
                "anyOf": [
                    {
                        "type": "string"
                    }, 
                    {
                        "type": "object", 
                        "properties": {
                            "representation": {
                                "items": {
                                    "type": "string"
                                }, 
                                "type": "array"
                            }, 
                            "display": {
                                "type": "string"
                            }
                        }
                    }
                ]
            }, 
            "type": "array", 
            "description": "Possible parameter format."
        }, 
        "action_ref": {
            "required": true, 
            "type": "string", 
            "description": "Reference to the aliased action."
        }, 
        "ref": {
            "type": "string", 
            "description": "System computed user friendly reference for the alias.                                 Provided value will be overridden by computed value."
        }, 
        "pack": {
            "required": true, 
            "type": "string", 
            "description": "The content pack this actionalias belongs to."
        }
    }, 
    "type": "object", 
    "description": "Alias for an action.", 
    "title": "ActionAlias"
}
